name: PR Automation

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a PR
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b my-branch
          git push origin my-branch
          gh pr create --title "Automated PR" --body "This is an automated pull request" --base main --head my-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
